decision_tree_1:
  - id: 1
    variable: match_progress
    condition: == 1
    left_id: 2
    right_id: 1
    action: ""
  - id: 2
    variable: match_remainder
    condition: "> 350"
    left_id: 3
    right_id: 6
    action: ""
  - id: 3
    variable: outpost
    condition: "< 500"
    left_id: 4
    right_id: 10
    action: ""
  - id: 4
    variable: sentry_hp
    condition: "< 150"
    left_id: 5
    right_id: 16
    action: ""
  - id: 5
    variable: ""
    condition: ""
    left_id: 1
    right_id: -1
    action: "1addblood-1"
  - id: 6
    variable: "match_remainder"
    condition: "> 210"
    left_id: 7
    right_id: 4
    action: ""
  - id: 7
    variable: "outpost"
    condition: "< 800"
    left_id: 8
    right_id: 10
    action: ""
  - id: 8
    variable: "sentry_hp"
    condition: "< 150"
    left_id: 9
    right_id: 16
    action: ""
  - id: 9
    variable: ""
    condition: ""
    left_id: 1
    right_id: -1
    action: "1addblood-1"
  - id: 10
    variable: sentry_bullet
    condition: "< 10"
    left_id: 11
    right_id: 17
    action: ""
  - id: 11
    variable: money
    condition: "> 300"
    left_id: 12
    right_id: 17
    action: ""
  - id: 12
    variable: bullet_remain_time
    condition: "< 1"
    left_id: 13
    right_id: 17
    action: ""
  - id: 13
    variable: on_addblood_area
    condition: "== 1"
    left_id: 14
    right_id: 15
    action: ""
  - id: 14
    variable: ""
    condition: ""
    left_id: 1
    right_id: -1
    action: "1buy_bullet-1-100"
  - id: 15
    variable: ""
    condition: ""
    left_id: 1
    right_id: -1
    action: "1addblood-1"
  - id: 16
    variable: sentry_bullet
    condition: "< 10"
    left_id: 19
    right_id: 18
    action: ""
  - id: 17
    variable: ""
    condition: ""
    left_id: 1
    right_id: -1
    action: "0attack-3.9-0"
  - id: 18
    variable: ""
    condition: ""
    left_id: 1
    right_id: -1
    action: "1home_range_move-4.16-0-5.5-0-4.16-1.8-5.5-1.4"
  - id: 19
    variable: money
    condition: "> 300"
    left_id: 20
    right_id: 18
    action: ""
  - id: 20
    variable: bullet_remain_time
    condition: "< 1"
    left_id: 13
    right_id: 18
    action: ""
